### ISSUE TITLE
Research about alternatives to Capacitive Sensors

### ISSUE THREAD

**Issue by Kushan-Nilanga** [Kushan-Nilanga/SIT329-Project#13]

**Comment by SachiniWitharana** [comment]
### **Photoelectric Sensor**
Photoelectric sensors use different technologies that address a variety of diverse application configurations. The common characteristic is that they all send out a beam light and then detect a change in the amount of light received back. The three most popular sensors are diffuse, reflective and through-beam. The light sources used – visible, infrared, LED or laser – will affect the sensing distance. In diffuse sensors, the presence of an object in the optical field of view causes diffused reflection of the beam. The receiver detects the light reflecting back from the object itself. Reflective and through-beam sensors create a beam of light and detect any opaque object that breaks the beam. Laser sensors can create a beam of light 50 meters or longer. Transparent objects, or objects with a varying surface finish, can be problematic for photoelectric sensors.

### **Ultrasonic Sensor**
These devices typically transmit a short burst of ultrasonic sound toward a target, which reflects the sound back to the sensor. The sound wave is well reflected by almost all dense materials (metal, wood, plastic, glass, liquid, etc.) and is not affected by color, transparent or shiny objects. Foam-like materials that absorb sound waves would not be a reliable application of this sensor type.

**How does Ultrasonic Proximity Sensor work?**
1.	The sonic transducer emits sonic waves
2.	Sonic waves bounce off the object
3.	The wave that bounced off is then returned to the sensor
4.	Time that it took to emit and receive sound waves is then used to determine distance/proximity

**Advantages of ultrasonic proximity sensors**

Contactless detection
Not affected by object color and transparency
Not affected by external environmental conditions, reliable solution
Works well in places with extreme conditions
Able to be used in dark environments
Low current consumption

**Disadvantages of ultrasonic proximity sensors**

Limited detection range though capable of higher range as compared to inductive and capacitive sensors
Doesn’t work in a vacuum since ultrasonic sensors operate via sound waves
Not able to measure the distance of Soft objects or ones with extreme textures

### **IR Proximity Sensor**

IR, in short for infrared, detects the presence of an object by emitting a beam of infrared light. It works similarly to ultrasonic sensors, though instead of using sonic waves, IR is transmitted.

Infrared proximity sensors consist of an IR LED that emits, and a light detector for detection of reflection. It has an in-built signal processing circuit determining an optical spot on the PSD.

**How do IR proximity sensors work?**

1. Infrared light is emitted from the IR LED emitter
2. The beam of light hits the object and gets reflected back in an angle
3. The reflected light will reach the light detector
4. The sensor in the light detector determines the position/distance of reflective object

**Advantages of IR proximity sensors**

Contactless detection
Applicable for daytime and nighttime usages
Secured communication through a line of sight
Able to measure the distance to soft objects unlike ultrasound proximity sensors
Accuracy of the infrared sensor not affected by corrosion or oxidation

**Disadvantages of IR proximity sensors**

Affected by environmental conditions and hard objects, implying inability fo usage through walls or doors
Requires line of sight between transmitter and receiver for communication
Performance dips over longer distances

**Comment by Kushan-Nilanga** [comment]
This is great research about alternatives to capacitive sensors. The advantages and disadvantages discussed allow us to pick the correct sensors. I believe this is now complete. We will revisit this if our attempts with capacitive sensors fail. 
Thanks.
